### ISSUE TITLE
Getting Set-Up

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#1]
Here are _some_ of the tasks for this week, 
- [ ] GitHub Account, Install Local GitHub client
- [ ] Bash/zsh Installed
- [ ] Become familiar with Markdown
- [ ] Install good Text Editor
- [ ] Install good Markdown Editor

Once completed, respond with
1. Your OS
2. Your Text Editor
3. Your Markdown Editor

**Comment by laurel-nave-powers** [comment]
1. macOS Catalina
2. Atom
3. Atom

**Comment by skreling** [comment]
1. macOS Big Sur
2. Atom
3. Atom

**Comment by jdduprey** [comment]
1. macOS
2. Atom
3. Atom

**Comment by afcoyle** [comment]
1. Windows (running WSL with Ubuntu)
2. Atom
3. Atom

**Comment by meganewing** [comment]
1. Mac
2. Atom
3. Atom

**Comment by Brybrio** [comment]
1. Windows - Virtual Machine with Ubuntu
2. Atom
3. Atom

**Comment by dippelmax** [comment]
1. MacOS 10.13.6
2. Atom
3. Atom
