### ISSUE TITLE
Using Jupyter and Blast

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#10]
This week you will use Blastx to compare a set of unknown nucleotide sequences to a known set of protein sequences.. specifically the Swiss-Prot sequences at https://www.uniprot.org/downloads.

Unless you already have a fasta use `http://eagle.fish.washington.edu/cnidarian/Ab_4denovo_CLC6_a.fa`

Show all of your work in Jupyter notebook that you push to the GitHub repo you created last week.

hints ... https://github.com/sr320/fun-gen/blob/master/Jupyter/03-Local-Blast.ipynb
AND [this screen recording](https://washington.zoom.us/rec/share/-BycPHgyMzFCrjAb-TOsFUPUibnoRGScQ3Tq9IXGyOsgIGYlXSNz-8GF7SUnVKx-.CWhnEbfLp3plNLI8)

Please add URL to your Jupyter notebook below once on GitHub.

**Comment by afcoyle** [comment]
[Finished - here's my Jupyter notebook!](https://github.com/fish546-2021/aidan-hematodinium/blob/main/projects/2021-01-18_Intro_to_Blastx/scripts/2021-01-18_Using_Jupyter_and_Blast.ipynb)

**Comment by skreling** [comment]
[https://github.com/fish546-2021/Sam-Metabarcoding/blob/main/Running_blast_in_Jupyter.ipynb](url)

**Comment by laurel-nave-powers** [comment]
https://github.com/fish546-2021/Laurel-genes/blob/main/0120-blast-quiz.ipynb 

I think I've run into an issue with the last part when running blastx. My computer just keeps spinning and working on it endlessly and never puts out any output.

**Comment by jdduprey** [comment]
[Joe's blast practice](https://github.com/fish546-2021/joe-benthos/blob/main/blastx_practice/code/blastx_practice.ipynb)

**Comment by meganewing** [comment]
https://github.com/fish546-2021/Megan-project/blob/main/0120-blast-quiz.ipynb

Holy heck, the last 3 commands took so long for my computer to finish. I started running them at 8:30!!! They just now finished lol

**Comment by Brybrio** [comment]
https://github.com/fish546-2021/Bryan-Eelgrass/blob/main/BABO-Blast-Practice.ipynb
