### ISSUE TITLE
First Steps in Project

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#12]
What do you imagine are the first three steps in your class project? Feel free to ask clarifying question in class or using issues..

**Comment by afcoyle** [comment]
1. Obtain two input files for GO_MWU for each combination of treatment conditions being examined
2. Perform enrichment analysis of each combo of treatment conditions with GO_MWU
3. Filter results of enrichment analysis to only include _Hematodinium_ genes (maybe this should be #1?)

**Comment by jdduprey** [comment]
1. Download the raw sequence files from the lab's github and ensure file integrity
2. Read through the original author's documentation and install the packages required for the pipeline they used. 
3. Read additional documentation for each step of the pipeline so I better understand the purpose/what/why of each step (remedial genetics/bioinformatics?)

**Comment by skreling** [comment]
1. Set up a conceptual framework of what you want to achieve with any given data set. Create some documentation on what some of these steps might be
2. Obtain data set that you can work with (in my case from Dryad)
3. Check the data out, make sure it looks reliable and begin formatting a workflow that will work with this data set. Read about different approaches and try in order of ease/efficiency as long as they give you what you want in the end.

**Comment by laurel-nave-powers** [comment]
1. Get and look through my dataset (from labmate) to understand exactly what it is and what is in it. From there I can figure out what kind of questions I can ask. 
2. Check the integrity of the data. Filter out low quality reads? 
3. Figure out how to mine SNPs and if I need to do anything to the dataset before doing it.

**Comment by dippelmax** [comment]
1. Figure out what questions I can ask with the data I have obtained. I am still working on figuring out what data I should use and understanding it. 
2. download the data and make sure the data is not corrupted in any way
3. View the data and prepare the data for analysis

**Comment by Brybrio** [comment]
1. Obtain and store my data. I am yet to receive my initial dataset and am not sure if I will get a hard copy or a download link. Also, I need to decide where to store this, including server (if my lab has any), hard drive, additional backup drives.
2. Make sure the data is ok to use, mainly readable and that it is good quality.
3. Learn the necessary commands to explore the dataset before further complicated analyses

**Comment by meganewing** [comment]
1. Get my data (currently working on it)
2. It'll be uploaded to online cloud storage so I'll need to download it and check its integrity
3. Look at the data and search literature to brainstorm what kind of analysis I want to do
