### ISSUE TITLE
Guide to Common Bioinformatics Data Formats

### ISSUE THREAD

**Issue by afcoyle** [sr320/course-fish546-2021#13]
I've often been feeling fairly lost when it comes to the various data formats out there - how a FASTA file differs from a FASTQ file, what a BED or a SAM file is, et cetera. 

In addition to knowing what all these formats are, I'd love to know what they do. What are the upsides and downsides of each format, under what circumstances is each preferable, and so on.

Essentially, if there's a good lengthy introduction to all these data formats out there, I'd love to check it out!

**Comment by sr320** [comment]
Best explanation of those file formats including what they do, ups and downs.... Chapters 10 and 11 in our textbook! 😄
