### ISSUE TITLE
Sudo installing from Jupyter notebook

### ISSUE THREAD

**Issue by Brybrio** [sr320/course-fish546-2021#19]
I was trying to sudo install curl from the Jupyter notebook but it would not work after asking for my password. It was easily fixed by running it in the command line, but just curious on how to get it done from Jupyter

**Comment by kubu4** [comment]
Just documenting discussion from class today.

Jupyter notebooks don't provide any sort of "interactive" interface. Generally, any commands that would require a response from the user won't work.
