### ISSUE TITLE
What do you hope to get out of the class?

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#2]

**Comment by laurel-nave-powers** [comment]
Get more comfortable with the skills and tools of bioinformatics so that I can use them later. Also, be able to understand the language used when I google for help.

**Comment by skreling** [comment]
Get more comfortable with pipelines for different bioinformatics projects for use in my own current research (genotyping, metabarcoding) and for the future

**Comment by jdduprey** [comment]
I would like to to become more comfortable with bioinformatic tools as well, especially running computationally intensive processes with open source resources. I'm looking forward to having time to make progress on my own metabarcoding project, and to have knowledgable people to reference when I make mistakes!

**Comment by meganewing** [comment]
Become more comfortable with bioinformatic tools by practicing with a data set in a structured way. Be able to exhibit some competency using these tools by the end of the quarter. And be less "scared" or intimidated by computing-heavy projects.

**Comment by Brybrio** [comment]
Learn about more tools to analyze my own extensive dataset for population structure and association mapping.

**Comment by afcoyle** [comment]
Get better at understanding how bioinformatics works - really get a good grasp of the principles and ideas. Plus make some progress on my own project!

**Comment by dippelmax** [comment]
I am interested in learning how bioinformatics tools work so I am able to analyse data conservation genetics projects in the future. I also would like some practice with coding in different languages because I need to become more comfortable with those skills.
