### ISSUE TITLE
Using Discussion on GitHub

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#28]
This week we will be transitioning to [Discussions](https://github.com/sr320/course-fish546-2021/discussions) on GitHub. Here is where you will ask (and answer questions) and share information. 

For this week please start at least one new Discussion in the "Show and tell" category where you show us, or tell us about something either you are proud of or you think would be helpful for others know.

Then drop a link below..

**Comment by skreling** [comment]
#32

**Comment by afcoyle** [comment]
[Here's mine!](https://github.com/sr320/course-fish546-2021/discussions/45)

**Comment by jdduprey** [comment]
[R basics](https://github.com/sr320/course-fish546-2021/discussions/47)

**Comment by laurel-nave-powers** [comment]
#50

**Comment by meganewing** [comment]
[Applications for BLAST and Uniprot](https://github.com/sr320/course-fish546-2021/discussions/51)

**Comment by dippelmax** [comment]
#52
