### ISSUE TITLE
Briefly describe your background in this area

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#3]

**Comment by skreling** [comment]
Roughly zero with bioinformatics pipelines, proficient in R, can usually (?) suffer through some python

**Comment by laurel-nave-powers** [comment]
I have a limited background in this area. In some previous classes I did a little bit of work in the terminal and have used BLAST. However, I didn't fully understand it when I was doing it. I don't really know python but have a little experience in R.

**Comment by jdduprey** [comment]
I have no experience with bioinformatics pipelines or BLAST. I have used R and python for data analysis, and have limited experience using the terminal.

**Comment by meganewing** [comment]
Some experience with R, command line, and blast. But definitely have a long way to go before I'm fully comfortable using any of these without guidance. Have used some sequence based tree construction programs like FigTree and MEGAX

**Comment by Brybrio** [comment]
A lot of experience with R, and some with command line, markdown, and BLAST. Usage of virtual machine running Linux/Ubuntu, and basic understanding/application of fastqc and stacks. Not much experience with Python.

**Comment by afcoyle** [comment]
About one quarter of working in the command line/markdown/BLAST doing Roberts lab work!

Plus a bit of Python and a decent amount of R

**Comment by dippelmax** [comment]
I have experience with R and have used BLAST before in a class. I don't have any experience using bioinformatics pipelines or python.
