### ISSUE TITLE
Navigating the commandline

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#5]
This week you will be completing the following tutorial.
https://github.com/sr320/course-fish546-2021/blob/master/01-Notes/Tutorials/Navigating-commandline.md

Try to complete prior to class on Thursday. And feel free to[ post an issue](https://github.com/sr320/course-fish546-2021/issues/new) if you have any questions.

Please paste in your commands (what you did in bash to complete the exercise)

**Comment by afcoyle** [comment]
```
whoami
cd /mnt/c/Users/acoyl/Documents/GradSchool/Classwork/Winter_2021/Bioinformatics_FISH546/Week_1/data
ls
cd users/nelle
ls
ls -F
ls -F data
ls -F /data
pwd
ls
cd data
pwd
ls -F
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
ls -F
mkdir thesis
ls -F
ls -F thesis
cd thesis
nano draft.txt
ls
rm draft.txt
ls
cd ..
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..
cd north-pacific-gyre/2012-07/03
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

```

**Comment by skreling** [comment]
whoami
cd Users/tracykreling/shell-novice/data
ls
cd users/nelle
ls
ls -F
ls -F data
ls -F /data
pwd
ls
cd data
pwd
ls -F
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
ls -F
mkdir thesis
ls -F
ls -F thesis
cd thesis
nano draft.txt
ls
rm draft.txt
ls
cd ..
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..
cd north-pacific-gyre/2012-07/03
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

**Comment by jdduprey** [comment]
pwd
whoami
cd /Users/dishajpatel/Desktop/shell-novice/data/users/nelle
ls
ls -F
ls -F data
ls -F /data
pwd
ls
cd data
pwd
ls -F
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
pwd
ls -F
mkdir thesis
ls -F
ls -F thesis
cd thesis
nano draft.txt
ls
rm draft.txt
ls
cd ..
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd..
cd north-pacific-gyre/2012-07-03
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

**Comment by laurel-nave-powers** [comment]
whoami 
pwd
cd Desktop/shell-novice/data/users/nelle
ls
ls -F
ls -F data 
ls -F /data
pwd
ls
cd data 
pwd
ls -F
pwd
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
ls -F
mkdir thesis 
ls -F 
ls -F thesis
cd thesis 
nano draft.txt
ls 
rm draft.txt
ls
ls molecules
cd ..
ls molecules
cd molecules
wc *.pdb
wc -1 *.pdb
wc -1 *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
cd ..
cd north-pacific-gyre/2012-07-03
wc -1 *.txt
wc -1 *.txt | sort -n | head -5 
wc -1 *.txt | sort -n | tail -5
ls *Z.txt

**Comment by meganewing** [comment]
whoami
pwd
cd Desktop/shell-novice/data/users/nelle
ls
ls -F
ls -F data 
ls -F /data
pwd
ls
cd data
pwd
ls -F
cd /users/nelle
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
pwd
ls -F
mkdir thesis
ls -F
ls -F thesis
cd thesis
nano draft.txt
ls
rm draft.txt 
ls
ls molecules
cd ..
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..
cd north-pacific-gyre/2012-07-03/
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

**Comment by dippelmax** [comment]
whoami
pwd
cd Desktop/Fish546/data/users/nelle
ls
ls -F
ls -F data
ls –F /data 
pwd
ls
cd data
pwd
ls -F
pwd
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
pwd
ls -F
ls -F thesis
cd thesis
nano draft.txt
It's not "publish or perish" anymore,                        
it's “share and thrive”.
Control O
(Unable to save the text) where I save the text?
Control X
ls
rm draft.txt
ls
pwd
cd..
ls
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..
cd north-pacific-gyre/2012-07-03/
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

**Comment by dippelmax** [comment]
whoami
pwd
cd Desktop/Fish546/data/users/nelle
ls
ls -F
ls -F data
ls –F /data 
pwd
ls
cd data
pwd
ls -F
pwd
cd ..
pwd
ls -F -a
ls north-pacific-gyre/2012-07-03/
pwd
ls -F
ls -F thesis
cd thesis
nano draft.txt
It's not "publish or perish" anymore,                        
it's “share and thrive”.
Control O
Control X
ls
rm draft.txt
ls
pwd
cd..
ls
ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..
cd north-pacific-gyre/2012-07-03/
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt

**Comment by Brybrio** [comment]
whoami
ls
cd Desktop/shell-novice/data
ls
cd users/nelle
ls
ls -F
ls -F data
ls -F /data
pwd
ls
cd data
pwd
ls -F
cd ..
pwd
ls -F -a


ls north-pacific-gyre/2012-07-03/
ls north-pacific-gyre/2012-07-03/

pwd
ls -F
mkdir thesis
ls -F
ls -F thesis
cd thesis
nano draft.txt
Ctrl+O
Ctrl+A
ls
rm draft.txt
ls
cd ..


ls molecules
cd molecules
wc *.pdb
wc -l *.pdb
wc -l *.pdb > lengths
ls lengths
cat lengths
sort -n lengths
sort -n lengths > sorted-lengths
head -1 sorted-lengths
sort -n lengths | head -1
wc -l *.pdb | sort -n | head -1
cd ..


cd north-pacific-gyre/2012-07/03
wc -l *.txt
wc -l *.txt | sort -n | head -5
wc -l *.txt | sort -n | tail -5
ls *Z.txt
