### ISSUE TITLE
Setting up Projects

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#6]
Based on the reading, what would you consider are the two most important things to consider when setting up a bioinformatics project?

**Comment by afcoyle** [comment]
1. Keep a cohesive, well-organized directory! All files for a single project inside one directory, clearly-named subdirectories, consistently-named files, and so on

2. Document in a README file! Describe where/when/how you obtained the data, document the versions of the software you're running, and which version of the data you're working with (if applicable)

**Comment by skreling** [comment]
1. Keep everything within a single directory with well-thought out names. Using leading zeroes.
2. Keep documentation for everything in README files. Document methods and workflows, origin of all data in project directory, when data is downloaded, version information, how data was downloaded
2.5. Take time to run quality controls

**Comment by jdduprey** [comment]
1. Creating a consistent directory structure so methods (and scripts) you use are reproducible for collaborators and for future you.
2.  Include documentation in README files of workflows, methods, metadata, and software version information.

**Comment by laurel-nave-powers** [comment]
1. Having good project organization- clearly named files (no spaces, include extensions) all organized in one project directory. This also helps with reproducibility.
2. Having a well documented project- document what you did, when you did it, and where you got it. This can be in a README file in your project’s main directory.

**Comment by meganewing** [comment]
1. Organization (setting up a project directory, sub directories, and sub projects. Naming directories and files in a way that is consistent and understandable)
2. Documentation (having a README file stored in your project's main direcories that includes information on software version, parameters used, workflow/methods, origin of data -- including where/when/how it was downloaded, data version, etc. And having this README file being in plain text so it can be viewed by any system any time)

Both of these are key to having a reproducible and robust project, and important for personal sanity when working with a lot of data.

**Comment by dippelmax** [comment]
The two most important things in setting up a bioinformatics project are documentation and organization. Documentation includes to keeping track of when, where and how data are downloaded. The text recommends storing it in plain-text README files which are portable and accessable. To organize the project, it is important to create a orderly directory with many subdirectories which are logically organized. It is imperative that your directory is understandable to you and to others who may seek to understand and/or reproduce your project.

**Comment by Brybrio** [comment]
The most important considerations according to the reading are directory organization and workflow documentation. I personally struggle with keeping file names consistent and subfolders organized, so I agree with the importance of standardizing names and folder organization. Also maintaining a record of the progress, code, file documentation, etc. is very necessary for future understanding and repeatability; using READMEs is a tip given in the reading.
