### ISSUE TITLE
FastQC

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#60]
What do you find the most useful output of FastQC?

**Comment by afcoyle** [comment]
Personally, I thought the graph for per sequence quality scores was simple but helpful. If we abide by the golden rule of not trusting your data or tools, then this graph seems to be a good place to look. If your sequences are low-quality, you'll be able to see so directly.

As a side note, some of the other outputs seem useful for other sorts of projects (for instance, per base sequence content), but since I'm working with RNA-Seq data, it's not too applicable

**Comment by skreling** [comment]
Similarly to what Aidan said, I think the per sequence quality scores were really useful. The desktop fastqc app is a really convenient way to quickly assess some standardized quality measures that you can compare across all of your samples and see what is good enough to continue on with in subsequent analyses and what might need more work computer or redoing lab work depending on what step of the process your in and what is plausible.

**Comment by jdduprey** [comment]
Echoing what other have said, I found the per base quality score graphic to be helpful and clear. Most of the graphic outputs I found helpful, and a good way to do a sanity check after downloading a sequence file. It seem like a step in the pipeline that could save a ton of trouble later, and like Sam said it runs quite quickly -at least with my practice file.

**Comment by laurel-nave-powers** [comment]
Of the FASTQC output, the per base sequence quality and the per base sequence content graphs seem like an easy way to get an overview of what is going on in your files and check the quality.

**Comment by Brybrio** [comment]
Given that basic summary information could be extracted with other simpler commands, I would consider that the simple Per base sequence quality is helpful to visually confirm that the quality of the reads were consistently adequate until the last bases sequenced.

**Comment by dippelmax** [comment]
The outputs of the per base sequence quality score and per sequence quality score seem like the most simplistic and useful metrics for checking the quality of your data. Comparing between a good and a bad sequence, it was the graph which most obviously showed something had gone wrong.

**Comment by meganewing** [comment]
Per base quality seemed really helpful because, in addition to the reasons joe, bryan, and max pointed out, I think the color coding helps make it really quick and easy to interpret your data's quality at a glance
