### ISSUE TITLE
Getting Moxy

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#61]
In preparation, for the potential use of Mox for your project and to become better prepared for using high-end compute resources. Initiate an account on Mox (via my lab) at https://robertslab.github.io/resources/mox_Adding-a-User/

at the URL to the GH issue request you make below.

**Comment by skreling** [comment]
https://github.com/RobertsLab/resources/issues/1089

**Comment by meganewing** [comment]
https://github.com/RobertsLab/resources/issues/1098

**Comment by jdduprey** [comment]
[access requested](https://github.com/RobertsLab/resources/issues/1100)

**Comment by laurel-nave-powers** [comment]
https://github.com/RobertsLab/resources/issues/1101

**Comment by Brybrio** [comment]
[Access Request](https://github.com/RobertsLab/resources/issues/1102#issue-800848865)
