### ISSUE TITLE
Draft project

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#69]
This week your draft project is due. Drop in url below when you have it complete.

- Your repo needs to be clearly organized (as discussed last week)
- Your readme file needs to describe the process and the general workflow, as well as alternatives.
- Raw data and intermediate file products (and end products) need to be accessible (link or location described in Readme for big files)
- Get some data to the "end" this mean (it needs to be clear in how this was done)
    - Rna-seq (count data)
    - Genetics (SNP info)
    - TaxaID (barcode/eDNA) - (table with taxa information)
- Have a written plan of what will happen in weeks 6-10 on your project (in Readme).

**Comment by laurel-nave-powers** [comment]
https://github.com/fish546-2021/Laurel-genes

**Comment by skreling** [comment]
https://github.com/fish546-2021/Sam-Metabarcoding

**Comment by aspencoyle** [comment]
https://github.com/fish546-2021/aidan-hematodinium
