### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#7]
Each student will have a "project" that results in a "product". Do you have any preference as to what such a project is involved with? What is one idea that comes to mind based on the reading and your interests? Please include any questions or concerns.

**Comment by afcoyle** [comment]
I think ideally, my project would essentially be continuing to progress on my analysis of differentially-expressed Hematodinium genes. If I complete that early (since I've already got a good head start), I can repeat with the other Hematodinium transcriptome - which, due to its size, would require me to figure out how to use Mox - and compare the two results

**Comment by skreling** [comment]
I currently don't have a dataset from my thesis, but it will be metabarcoding from coyote scats. I've found a few options for datasets that should be pretty similar, so I'd like to work on analyzing metabarcoding data from a few different diet metabarcoding diet studies that should have amplified reads from vertebrates, invertebrates and plants

**Comment by jdduprey** [comment]
I would like to work with the Hood Canal/San Juans eDNA sequence data that I will be working with for my thesis. First, I would like to reproduce workflows on sequence data that has already been processed by the lab. Then, I would like to take unprocessed sequence data all the way through to analysis of benthic community structure.

**Comment by meganewing** [comment]
I don't currently have a dataset, but I'm interested in reproduction and stress, so I think the data I will most likely encounter in the future will be RNAseq data for genes associated with reproductive development, or differential gene expression in response to stress. If I am able to center my project around that kind of data, it would be the most useful for me to learn considering my long term goals. 
However, I'm unsure of the "product" I would be aiming for considering the timeline of this class, so guidance on that would be very helpful.

**Comment by dippelmax** [comment]
I do not currently have a dataset. I am interested in conservation genetics, specifically how genetic diversity of wildlife populations is affected by habitat fragmentation. I emailed a potential graduate advisor who works with primate genetics, so hopefully he has some data I can use. I would also be more than happy to use some data from your lab whether or not it is super relevant to my long-term research interest.

**Comment by Brybrio** [comment]
I am expecting to receive my initial dataset around the end of the month. These data will focus on determining population structure of eelgrass in WA State. If this data isn't delivered soon, then I will likely work with salmon data to build pedigrees or for population assignment as well.

**Comment by laurel-nave-powers** [comment]
I do not currently have a dataset. In the future I may potentially be using mtDNA and PCR based restriction fragment length polymorphism (RFLP) to ID larval fish that cannot be identified with morphology alone. So, learning how to navigate data like this would be helpful for me long term. If my project for this class had similar data to work with that would be great. I also am not sure of what product I would be aiming for with this project.
