### ISSUE TITLE
Scripting 

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#77]
Create a 1) script,  AND  either
a  jupyter notebook, or R markdown file 
that performs a relevant operation(s) on a number of files (>4) "automatically".

This should be in your class repo and should be written in a manner that when I clone the repo I can generate the output.

For instance, the files will need to be in the repo or the script will need to be able to pull them from a public url. Note absolute paths will not work.

please place the url to the script, jupyter notebook, or R markdown file below.

**Comment by aspencoyle** [comment]
https://github.com/fish546-2021/aidan-hematodinium/blob/main/projects/hematodinium_analysis/scripts/11_obtaining_TPM_for_DEGs.Rmd

Loops over kallisto output files, selects a column, and left joins it onto an existing table

**Comment by skreling** [comment]
https://github.com/fish546-2021/Sam-Metabarcoding/blob/main/Assignments/Create_a_Script.Rmd

Takes input fastq or fastq.gz files and creates a combined plot of all figures showing sample quality scores and writes the figure to a specified directory using DADA2. Note that output plot is sent to "results" folder

Also did this *very* small xargs script to remove unnecessary .fasta files
https://github.com/fish546-2021/Sam-Metabarcoding/blob/main/Assignments/Assignment_script2.ipynb

**Comment by meganewing** [comment]
runs fastqc for "all" my raw data files (all meaning as many as are on gannet....waiting for an update on the whole ostrich issue to transfer rest of the files to gannet)

https://github.com/fish546-2021/Megan-project/blob/main/code/0218-fastqcAutoForMultipleFiles.ipynb

**Comment by laurel-nave-powers** [comment]
https://github.com/fish546-2021/Laurel-genes/blob/main/546_R_HW/546_R_HW/546_R_HW_script.Rmd

**Comment by Brybrio** [comment]
https://github.com/fish546-2021/Bryan-Eelgrass/blob/main/Scripts/Stacks_long.ipynb

**Comment by jdduprey** [comment]
I uploaded a subset of data to Gannet, working on a [script](https://github.com/fish546-2021/joe-benthos/blob/main/code/04-gannet-metadata.ipynb) to download and unzip files from there instead of from the google drive. Still a work in progress.
