### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#78]
Generate at least one visualization that represents your project. Include it in our repo and add URL below

**Comment by aspencoyle** [comment]
I interpreted this as "outline of project inputs and workflow" - hopefully that's correct! Here's my visualization:

https://github.com/fish546-2021/aidan-hematodinium/blob/main/projects/hematodinium_analysis/graphs/project_outline_visualization.pdf

**Comment by skreling** [comment]
Here's my visualization of my work flow. This was created using ObiTools and the wolf diet dataset 

https://github.com/fish546-2021/Sam-Metabarcoding/blob/main/Results/Wolf/wolf.pdf

**Comment by meganewing** [comment]
I interpreted this the same way as Aidan since its representing the project not just a visualization of our outputs 
https://github.com/fish546-2021/Megan-project/blob/main/0218-projectVisualMap.jpg

**Comment by laurel-nave-powers** [comment]
https://github.com/fish546-2021/Laurel-genes/blob/main/project_visualization.pdf

**Comment by jdduprey** [comment]
Effectively visualizing community structure seems to be quite challenging. [This](https://github.com/fish546-2021/joe-benthos/blob/main/analysis/rough_treemap.jpeg) is my first attempt at just seeing what is in the output taxa tables when all the output data is aggregated. I think a stacked bar chart might be more effective as I break the data down by sampling event. 

Apologies for the eye burning color palette... 
Tree-map and data processing code [here](https://github.com/fish546-2021/joe-benthos/blob/main/analysis/02-dataviz.R).

**Comment by meganewing** [comment]
@jdduprey you say eye burning color palette... I say modern art. lol

**Comment by sr320** [comment]
@skreling very nice - what software did you use to create this?

**Comment by skreling** [comment]
@sr320 
ObiTools! It keeps track of all the commands you use and you can have it print the workflow at the end in this flow diagram.
