### ISSUE TITLE
Create an Issue

### ISSUE THREAD

**Issue by sr320** [sr320/course-fish546-2021#9]
Identify at least one issue you would like assistance on relating to one of the following topics
- Bash 
- GitHub
- Jupyter
- Your data

It could be how to do a simple task, improve your current workflow, reduce redundant actions, or a simple curiosity etc.
**Once you [create an issue](https://github.com/sr320/course-fish546-2021/issues/new)**

add the url below

**Comment by afcoyle** [comment]
https://github.com/sr320/course-fish546-2021/issues/13

**Comment by laurel-nave-powers** [comment]
#14 
https://github.com/sr320/course-fish546-2021/issues/14

**Comment by jdduprey** [comment]
[directory madness](https://github.com/sr320/course-fish546-2021/issues/15)

**Comment by skreling** [comment]
#16

**Comment by meganewing** [comment]
https://github.com/sr320/course-fish546-2021/issues/17#issue-790582839

**Comment by dippelmax** [comment]
#18

**Comment by Brybrio** [comment]
[#19 ](url)
